In [2]:
import os
import pandas as pd
import kagglehub
path = kagglehub.dataset_download("silicon99/dft-accident-data")
print("Path to dataset files:", path)
data_path=os.path.join(path, "Accidents0515.csv")
df=pd.read_csv(data_path)

Path to dataset files: C:\Users\lalaq\.cache\kagglehub\datasets\silicon99\dft-accident-data\versions\3

In [3]:
df.head()

,Accident_Index,Location_Easting_OSGR,Location_Northing_OSGR,Longitude,Latitude,Police_Force,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Date,...,Pedestrian_Crossing-Human_Control,Pedestrian_Crossing-Physical_Facilities,Light_Conditions,Weather_Conditions,Road_Surface_Conditions,Special_Conditions_at_Site,Carriageway_Hazards,Urban_or_Rural_Area,Did_Police_Officer_Attend_Scene_of_Accident,LSOA_of_Accident_Location
0,200501BS00001,525680.0,178240.0,-0.191170,51.489096,1,2,1,1,04/01/2005,...,0,1,1,2,2,0,0,1,1,E01002849
1,200501BS00002,524170.0,181650.0,-0.211708,51.520075,1,3,1,1,05/01/2005,...,0,5,4,1,1,0,0,1,1,E01002909
2,200501BS00003,524520.0,182240.0,-0.206458,51.525301,1,3,2,1,06/01/2005,...,0,0,4,1,1,0,0,1,1,E01002857
3,200501BS00004,526900.0,177530.0,-0.173862,51.482442,1,3,1,1,07/01/2005,...,0,0,1,1,1,0,0,1,1,E01002840
4,200501BS00005,528060.0,179040.0,-0.156618,51.495752,1,3,1,1,10/01/2005,...,0,0,7,1,2,0,0,1,1,E01002863

In [4]:
for column in df.columns:
    print(column)

Accident_Index
Location_Easting_OSGR
Location_Northing_OSGR
Longitude
Latitude
Police_Force
Accident_Severity
Number_of_Vehicles
Number_of_Casualties
Date
Day_of_Week
Time
Local_Authority_(District)
Local_Authority_(Highway)
1st_Road_Class
1st_Road_Number
Road_Type
Speed_limit
Junction_Detail
Junction_Control
2nd_Road_Class
2nd_Road_Number
Pedestrian_Crossing-Human_Control
Pedestrian_Crossing-Physical_Facilities
Light_Conditions
Weather_Conditions
Road_Surface_Conditions
Special_Conditions_at_Site
Carriageway_Hazards
Urban_or_Rural_Area
Did_Police_Officer_Attend_Scene_of_Accident
LSOA_of_Accident_Location

In [5]:
selected_columns = [
    'Accident_Index',
    'Longitude',
    'Latitude',
    'Accident_Severity',
    'Date',
    'Time',
    'Day_of_Week',
    'Number_of_Vehicles',
    'Number_of_Casualties',
    'Road_Type',
    'Speed_limit',
    'Junction_Detail',
    'Junction_Control',
    'Light_Conditions',
    'Weather_Conditions',
    'Road_Surface_Conditions',
    'Urban_or_Rural_Area'
]

In [6]:
accidents_df = df[selected_columns]

In [7]:
accidents_df.head()

,Accident_Index,Longitude,Latitude,Accident_Severity,Date,Time,Day_of_Week,Number_of_Vehicles,Number_of_Casualties,Road_Type,Speed_limit,Junction_Detail,Junction_Control,Light_Conditions,Weather_Conditions,Road_Surface_Conditions,Urban_or_Rural_Area
0,200501BS00001,-0.191170,51.489096,2,04/01/2005,17:42,3,1,1,6,30,0,-1,1,2,2,1
1,200501BS00002,-0.211708,51.520075,3,05/01/2005,17:36,4,1,1,3,30,6,2,4,1,1,1
2,200501BS00003,-0.206458,51.525301,3,06/01/2005,00:15,5,2,1,6,30,0,-1,4,1,1,1
3,200501BS00004,-0.173862,51.482442,3,07/01/2005,10:35,6,1,1,6,30,0,-1,1,1,1,1
4,200501BS00005,-0.156618,51.495752,3,10/01/2005,21:13,2,1,1,6,30,0,-1,7,1,2,1

In [8]:
accidents_df.shape

(1780653, 17)

In [9]:
accidents_df['Date'] = pd.to_datetime(
    accidents_df['Date'],
    dayfirst=True,
    errors='coerce'
)

In [10]:
accidents_df = accidents_df[
    accidents_df['Date'].dt.year.isin([2013, 2014, 2015])
].copy()

In [11]:
accidents_df['Year'] = accidents_df['Date'].dt.year

In [12]:
accidents_df['Year'].value_counts().sort_index()

Year
2013    138660
2014    146322
2015    140056
Name: count, dtype: int64

In [13]:
accidents_df.shape

(425038, 18)

In [14]:
accidents_df.head()

,Accident_Index,Longitude,Latitude,Accident_Severity,Date,Time,Day_of_Week,Number_of_Vehicles,Number_of_Casualties,Road_Type,Speed_limit,Junction_Detail,Junction_Control,Light_Conditions,Weather_Conditions,Road_Surface_Conditions,Urban_or_Rural_Area,Year
1355615,201301BS70003,-0.171402,51.486361,2,2013-01-02,09:08,4,2,1,6,30,3,4,1,1,1,1,2013
1355616,201301BS70005,-0.173356,51.495115,3,2013-01-04,08:16,6,1,2,6,30,6,2,1,8,1,1,2013
1355617,201301BS70006,-0.210767,51.518353,3,2013-01-07,11:45,2,1,1,6,30,6,4,1,1,1,1,2013
1355618,201301BS70007,-0.209675,51.516808,3,2013-01-10,10:40,5,2,1,6,30,6,2,1,1,1,1,2013
1355619,201301BS70009,-0.194332,51.492922,3,2013-01-04,17:47,6,2,1,2,30,3,4,4,1,1,1,2013

In [15]:
accidents_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 425038 entries, 1355615 to 1780652
Data columns (total 18 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Accident_Index           425038 non-null  str
 1   Longitude                425011 non-null  float64
 2   Latitude                 425011 non-null  float64
 3   Accident_Severity        425038 non-null  int64
 4   Date                     425038 non-null  datetime64[us]
 5   Time                     425012 non-null  str
 6   Day_of_Week              425038 non-null  int64
 7   Number_of_Vehicles       425038 non-null  int64
 8   Number_of_Casualties     425038 non-null  int64
 9   Road_Type                425038 non-null  int64
 10  Speed_limit              425038 non-null  int64
 11  Junction_Detail          425038 non-null  int64
 12  Junction_Control         425038 non-null  int64
 13  Light_Conditions         425038 non-null  int64
 14  Weather_Conditions       425038 non-null  int64
 15  Road_Surface_Conditions  425038 non-null  int64
 16  Urban_or_Rural_Area      425038 non-null  int64
 17  Year                     425038 non-null  int32
dtypes: datetime64[us](1), float64(2), int32(1), int64(12), str(2)
memory usage: 56.7 MB

In [16]:
accidents_df.isnull().sum()

Accident_Index              0
Longitude                  27
Latitude                   27
Accident_Severity           0
Date                        0
Time                       26
Day_of_Week                 0
Number_of_Vehicles          0
Number_of_Casualties        0
Road_Type                   0
Speed_limit                 0
Junction_Detail             0
Junction_Control            0
Light_Conditions            0
Weather_Conditions          0
Road_Surface_Conditions     0
Urban_or_Rural_Area         0
Year                        0
dtype: int64

In [17]:
missing_values = accidents_df.isnull().sum()

missing_values[missing_values > 0].sort_values(ascending=False)

Longitude    27
Latitude     27
Time         26
dtype: int64

In [18]:
accidents_df.duplicated().sum()

np.int64(0)

In [19]:
accidents_df['Accident_Index'].duplicated().sum()

np.int64(0)

In [20]:
accidents_df['Accident_Severity'].value_counts().sort_index()

Accident_Severity
1      4882
2     60338
3    359818
Name: count, dtype: int64

In [21]:
accidents_df['Accident_Severity'].value_counts(
    normalize=True
).sort_index() * 100

Accident_Severity
1     1.148603
2    14.195907
3    84.655490
Name: proportion, dtype: float64

In [22]:
accidents_df['Year'].value_counts().sort_index()

Year
2013    138660
2014    146322
2015    140056
Name: count, dtype: int64

In [23]:
accidents_df.describe()

,Longitude,Latitude,Accident_Severity,Date,Day_of_Week,Number_of_Vehicles,Number_of_Casualties,Road_Type,Speed_limit,Junction_Detail,Junction_Control,Light_Conditions,Weather_Conditions,Road_Surface_Conditions,Urban_or_Rural_Area,Year
count,425011.000000,425011.000000,425038.000000,425038,425038.000000,425038.000000,425038.000000,425038.000000,425038.000000,425038.000000,425038.000000,425038.000000,425038.000000,425038.000000,425038.000000,425038.000000
mean,-1.340951,52.509533,2.835069,2014-07-07 20:14:15.723959,4.102610,1.833448,1.327731,5.168286,38.312598,2.310111,1.814727,1.943360,1.518184,1.324667,1.345077,2014.003284
min,-7.489410,49.912941,1.000000,2013-01-01 00:00:00,1.000000,1.000000,1.000000,1.000000,0.000000,-1.000000,-1.000000,1.000000,1.000000,-1.000000,1.000000,2013.000000
25%,-2.239151,51.475093,3.000000,2013-10-14 00:00:00,2.000000,1.000000,1.000000,6.000000,30.000000,0.000000,-1.000000,1.000000,1.000000,1.000000,1.000000,2013.000000
50%,-1.253958,52.066193,3.000000,2014-07-08 00:00:00,4.000000,2.000000,1.000000,6.000000,30.000000,3.000000,3.000000,1.000000,1.000000,1.000000,1.000000,2014.000000
75%,-0.175308,53.420564,3.000000,2015-04-03 00:00:00,6.000000,2.000000,1.000000,6.000000,40.000000,3.000000,4.000000,4.000000,1.000000,2.000000,2.000000,2015.000000
max,1.758797,60.661117,3.000000,2015-12-31 00:00:00,7.000000,67.000000,93.000000,9.000000,70.000000,9.000000,4.000000,7.000000,9.000000,5.000000,2.000000,2015.000000
std,1.398767,1.430370,0.400876,NaN,1.914098,0.712014,0.819154,1.640664,13.900159,2.502453,2.345225,1.647492,1.536325,0.582786,0.475394,0.809774

In [24]:
print("Cleaning-dən əvvəlki vəziyyət:", accidents_df.shape)

Cleaning-dən əvvəlki vəziyyət: (425038, 18)

In [25]:
accidents_df = accidents_df.dropna(
    subset=['Longitude', 'Latitude', 'Time']
).copy()

In [26]:
print("Cleaning-dən sonrakı vəziyyət:", accidents_df.shape)

accidents_df[
    ['Longitude', 'Latitude', 'Time']
].isnull().sum()

Cleaning-dən sonrakı vəziyyət: (424985, 18)

Longitude    0
Latitude     0
Time         0
dtype: int64

In [27]:
severity_names = {
    1: 'Fatal',
    2: 'Serious',
    3: 'Slight'
}

accidents_df['Severity_Label'] = accidents_df[
    'Accident_Severity'
].map(severity_names)

In [28]:
accidents_df[
    ['Accident_Severity', 'Severity_Label']
].head()

         Accident_Severity Severity_Label
1355615                  2        Serious
1355616                  3         Slight
1355617                  3         Slight
1355618                  3         Slight
1355619                  3         Slight

In [29]:
accidents_df['Severe_Accident'] = accidents_df[
    'Accident_Severity'
].isin([1, 2]).astype(int)

In [30]:
accidents_df['Severe_Accident'].value_counts()

Severe_Accident
0    359777
1     65208
Name: count, dtype: int64

In [31]:
accidents_df['Severe_Accident'].value_counts(
    normalize=True
) * 100

Severe_Accident
0    84.6564
1    15.3436
Name: proportion, dtype: float64

In [32]:
accidents_df['Accident_DateTime'] = pd.to_datetime(
    accidents_df['Date'].astype(str)
    + ' '
    + accidents_df['Time'],
    errors='coerce'
)

In [33]:
accidents_df['Month'] = accidents_df[
    'Accident_DateTime'
].dt.month

accidents_df['Hour'] = accidents_df[
    'Accident_DateTime'
].dt.hour

In [34]:
accidents_df['Weather_Hour'] = accidents_df[
    'Accident_DateTime'
].dt.floor('h')

In [35]:
accidents_df[
    [
        'Date',
        'Time',
        'Accident_DateTime',
        'Year',
        'Month',
        'Hour',
        'Weather_Hour'
    ]
].head()

,Date,Time,Accident_DateTime,Year,Month,Hour,Weather_Hour
1355615,2013-01-02,09:08,2013-01-02 09:08:00,2013,1,9,2013-01-02 09:00:00
1355616,2013-01-04,08:16,2013-01-04 08:16:00,2013,1,8,2013-01-04 08:00:00
1355617,2013-01-07,11:45,2013-01-07 11:45:00,2013,1,11,2013-01-07 11:00:00
1355618,2013-01-10,10:40,2013-01-10 10:40:00,2013,1,10,2013-01-10 10:00:00
1355619,2013-01-04,17:47,2013-01-04 17:47:00,2013,1,17,2013-01-04 17:00:00

In [36]:
accidents_df = accidents_df.dropna(
    subset=['Longitude', 'Latitude', 'Time']
)

accidents_df.shape

(424985, 24)

In [37]:
accidents_df[
    ['Longitude', 'Latitude', 'Time']
].isnull().sum()

Longitude    0
Latitude     0
Time         0
dtype: int64

In [38]:
accidents_df[
    [
        'Accident_Severity',
        'Severity_Label',
        'Severe_Accident',
        'Accident_DateTime',
        'Month',
        'Hour',
        'Weather_Hour'
    ]
].head()

,Accident_Severity,Severity_Label,Severe_Accident,Accident_DateTime,Month,Hour,Weather_Hour
1355615,2,Serious,1,2013-01-02 09:08:00,1,9,2013-01-02 09:00:00
1355616,3,Slight,0,2013-01-04 08:16:00,1,8,2013-01-04 08:00:00
1355617,3,Slight,0,2013-01-07 11:45:00,1,11,2013-01-07 11:00:00
1355618,3,Slight,0,2013-01-10 10:40:00,1,10,2013-01-10 10:00:00
1355619,3,Slight,0,2013-01-04 17:47:00,1,17,2013-01-04 17:00:00

In [39]:
accidents_df['Severe_Accident'].value_counts()

Severe_Accident
0    359777
1     65208
Name: count, dtype: int64

In [40]:
accidents_df['Severe_Accident'].value_counts(normalize=True) * 100

Severe_Accident
0    84.6564
1    15.3436
Name: proportion, dtype: float64

In [41]:
accidents_df['Accident_DateTime'].isnull().sum()

np.int64(0)

In [42]:
accidents_df[
    ['Latitude', 'Longitude']
].describe()

            Latitude      Longitude
count  424985.000000  424985.000000
mean       52.509343      -1.340903
std         1.430141       1.398791
min        49.912941      -7.489410
25%        51.475090      -2.239121
50%        52.066064      -1.253795
75%        53.420475      -0.175284
max        60.661117       1.758797

In [43]:
accidents_df['Grid_Latitude'] = accidents_df[
    'Latitude'
].round(1)

accidents_df['Grid_Longitude'] = accidents_df[
    'Longitude'
].round(1)

In [44]:
accidents_df[
    ['Grid_Latitude', 'Grid_Longitude']
].drop_duplicates().shape

(3069, 2)

In [45]:
police_df = df[['Accident_Index', 'Police_Force']]
police_df.head()

  Accident_Index  Police_Force
0  200501BS00001             1
1  200501BS00002             1
2  200501BS00003             1
3  200501BS00004             1
4  200501BS00005             1

In [46]:
accidents_df = accidents_df.merge(
    police_df,
    on='Accident_Index',
    how='left'
)

In [47]:
accidents_df['Police_Force'].isnull().sum()

np.int64(0)

In [48]:
accidents_df = accidents_df[
    accidents_df['Police_Force'].isin([1, 48])
].copy()

In [49]:
accidents_df.shape

(74359, 27)

In [50]:
accidents_df['Year'].value_counts().sort_index()

Year
2013    23097
2014    26030
2015    25232
Name: count, dtype: int64

In [51]:
accidents_df[
    ['Grid_Latitude', 'Grid_Longitude']
].drop_duplicates().shape

(34, 2)

In [52]:
accidents_df['Year'].value_counts().sort_index()

Year
2013    23097
2014    26030
2015    25232
Name: count, dtype: int64

In [53]:
accidents_df['Severity_Label'].value_counts()

Severity_Label
Slight     67999
Serious     5973
Fatal        387
Name: count, dtype: int64

In [54]:
accidents_df['Severe_Accident'].value_counts(normalize=True) * 100

Severe_Accident
0    91.4469
1     8.5531
Name: proportion, dtype: float64

In [55]:
accidents_df = accidents_df.reset_index(drop=True)

In [56]:
accidents_df.head()

,Accident_Index,Longitude,Latitude,Accident_Severity,Date,Time,Day_of_Week,Number_of_Vehicles,Number_of_Casualties,Road_Type,...,Year,Severity_Label,Severe_Accident,Accident_DateTime,Month,Hour,Weather_Hour,Grid_Latitude,Grid_Longitude,Police_Force
0,201301BS70003,-0.171402,51.486361,2,2013-01-02,09:08,4,2,1,6,...,2013,Serious,1,2013-01-02 09:08:00,1,9,2013-01-02 09:00:00,51.5,-0.2,1
1,201301BS70005,-0.173356,51.495115,3,2013-01-04,08:16,6,1,2,6,...,2013,Slight,0,2013-01-04 08:16:00,1,8,2013-01-04 08:00:00,51.5,-0.2,1
2,201301BS70006,-0.210767,51.518353,3,2013-01-07,11:45,2,1,1,6,...,2013,Slight,0,2013-01-07 11:45:00,1,11,2013-01-07 11:00:00,51.5,-0.2,1
3,201301BS70007,-0.209675,51.516808,3,2013-01-10,10:40,5,2,1,6,...,2013,Slight,0,2013-01-10 10:40:00,1,10,2013-01-10 10:00:00,51.5,-0.2,1
4,201301BS70009,-0.194332,51.492922,3,2013-01-04,17:47,6,2,1,2,...,2013,Slight,0,2013-01-04 17:47:00,1,17,2013-01-04 17:00:00,51.5,-0.2,1

In [57]:
os.makedirs("data", exist_ok=True)
accidents_df.to_csv("data/accidents_london_2013_2015.csv", index=False)

In [58]:
print(accidents_df.shape)

(74359, 27)

In [59]:
import requests

In [60]:
test_latitude = accidents_df.loc[0, 'Grid_Latitude']
test_longitude = accidents_df.loc[0, 'Grid_Longitude']
test_date = accidents_df.loc[0, 'Date'].strftime('%Y-%m-%d')

print(test_latitude)
print(test_longitude)
print(test_date)

51.5
-0.2
2013-01-02

In [61]:
weather_url = 'https://archive-api.open-meteo.com/v1/archive'

weather_params = {
    'latitude': test_latitude,
    'longitude': test_longitude,
    'start_date': test_date,
    'end_date': test_date,
    'hourly': [
        'temperature_2m',
        'rain',
        'snowfall',
        'weather_code',
        'cloud_cover',
        'wind_speed_10m'
    ],
    'timezone': 'Europe/London'
}

response = requests.get(
    weather_url,
    params=weather_params,
    timeout=60
)

print(response.status_code)

200

In [62]:
weather_data = response.json()

weather_data.keys()

dict_keys(['latitude', 'longitude', 'generationtime_ms', 'utc_offset_seconds', 'timezone', 'timezone_abbreviation', 'elevation', 'hourly_units', 'hourly'])

In [63]:
weather_test_df = pd.DataFrame(
    weather_data['hourly']
)

weather_test_df.head()

,time,temperature_2m,rain,snowfall,weather_code,cloud_cover,wind_speed_10m
0,2013-01-02T00:00,4.7,0.0,0.0,1,22,15.9
1,2013-01-02T01:00,4.1,0.0,0.0,1,39,15.9
2,2013-01-02T02:00,3.6,0.0,0.0,2,76,16.0
3,2013-01-02T03:00,3.3,0.0,0.0,2,74,15.2
4,2013-01-02T04:00,3.2,0.0,0.0,1,23,14.9

In [64]:
weather_test_df.shape

(24, 7)

In [65]:
weather_test_df.columns

Index(['time', 'temperature_2m', 'rain', 'snowfall', 'weather_code',
       'cloud_cover', 'wind_speed_10m'],
      dtype='str')

In [66]:
grid_df = accidents_df[
    ['Grid_Latitude', 'Grid_Longitude']
].drop_duplicates().reset_index(drop=True)

grid_df.shape

(34, 2)

In [67]:
weather_list = []

In [68]:
import time

In [69]:
for i in range(len(grid_df)):

    time.sleep(10)

    latitude = grid_df.loc[i, 'Grid_Latitude']
    longitude = grid_df.loc[i, 'Grid_Longitude']

    weather_params = {
        'latitude': latitude,
        'longitude': longitude,
        'start_date': '2013-01-01',
        'end_date': '2015-12-31',
        'hourly': [
            'temperature_2m',
            'rain',
            'snowfall',
            'weather_code',
            'cloud_cover',
            'wind_speed_10m'
        ],
        'timezone': 'Europe/London'
    }

    response = requests.get(
        weather_url,
        params=weather_params,
        timeout=120
    )

    if response.status_code == 200:

        weather_data = response.json()

        temp_df = pd.DataFrame(
            weather_data['hourly']
        )

        temp_df['Grid_Latitude'] = latitude
        temp_df['Grid_Longitude'] = longitude

        weather_list.append(temp_df)

        print(i + 1, 'of', len(grid_df), 'completed')

    else:
        print(
            'Error:',
            latitude,
            longitude,
            response.status_code
        )

1 of 34 completed
2 of 34 completed
3 of 34 completed
4 of 34 completed
5 of 34 completed
6 of 34 completed
7 of 34 completed
8 of 34 completed
9 of 34 completed
10 of 34 completed
11 of 34 completed
12 of 34 completed
13 of 34 completed
14 of 34 completed
15 of 34 completed
16 of 34 completed
17 of 34 completed
18 of 34 completed
19 of 34 completed
20 of 34 completed
21 of 34 completed
22 of 34 completed
23 of 34 completed
24 of 34 completed
25 of 34 completed
26 of 34 completed
27 of 34 completed
28 of 34 completed
29 of 34 completed
30 of 34 completed
31 of 34 completed
32 of 34 completed
33 of 34 completed
34 of 34 completed

In [70]:
completed_grids = []

for data in weather_list:
    latitude = data['Grid_Latitude'].iloc[0]
    longitude = data['Grid_Longitude'].iloc[0]

    completed_grids.append((latitude, longitude))

print('Completed grids:', len(completed_grids))

Completed grids: 34

In [71]:
for i in range(len(grid_df)):

    latitude = grid_df.loc[i, 'Grid_Latitude']
    longitude = grid_df.loc[i, 'Grid_Longitude']

    if (latitude, longitude) in completed_grids:
        continue

    weather_params = {
        'latitude': latitude,
        'longitude': longitude,
        'start_date': '2013-01-01',
        'end_date': '2015-12-31',
        'hourly': [
            'temperature_2m',
            'rain',
            'snowfall',
            'weather_code',
            'cloud_cover',
            'wind_speed_10m'
        ],
        'timezone': 'Europe/London'
    }

    success = False

    while success == False:

        response = requests.get(
            weather_url,
            params=weather_params,
            timeout=120
        )

        if response.status_code == 200:

            weather_data = response.json()

            temp_df = pd.DataFrame(
                weather_data['hourly']
            )

            temp_df['Grid_Latitude'] = latitude
            temp_df['Grid_Longitude'] = longitude

            weather_list.append(temp_df)
            completed_grids.append((latitude, longitude))

            print(
                len(completed_grids),
                'of',
                len(grid_df),
                'completed'
            )

            success = True

            time.sleep(15)

        elif response.status_code == 429:

            print('Rate limit. Retrying this grid...')

            time.sleep(60)

        else:

            print(
                'Error:',
                latitude,
                longitude,
                response.status_code
            )

            success = True

In [72]:
len(weather_list)

34

In [73]:
weather_df = pd.concat(
    weather_list,
    ignore_index=True
)

weather_df.shape

(893520, 9)

In [74]:
weather_df.duplicated(
    subset=[
        'Grid_Latitude',
        'Grid_Longitude',
        'time'
    ]
).sum()

np.int64(0)

In [75]:
weather_df['time'] = pd.to_datetime(
    weather_df['time'],
    errors='coerce'
)

In [76]:
weather_df = weather_df.rename(
    columns={'time': 'Weather_Hour'}
)

In [77]:
weather_df.isnull().sum()

Weather_Hour      0
temperature_2m    0
rain              0
snowfall          0
weather_code      0
cloud_cover       0
wind_speed_10m    0
Grid_Latitude     0
Grid_Longitude    0
dtype: int64

In [78]:
print(weather_df['Weather_Hour'].min())
print(weather_df['Weather_Hour'].max())

2013-01-01 00:00:00
2015-12-31 23:00:00

In [79]:
weather_df.to_csv("data/weather_london_2013_2015.csv", index=False)
print('Weather dataset saved')
print(weather_df.shape)

Weather dataset saved
(893520, 9)

In [80]:
print(accidents_df['Weather_Hour'].dtype)
print(weather_df['Weather_Hour'].dtype)

datetime64[us]
datetime64[us]

In [81]:
print('Merge-dən əvvəl:', accidents_df.shape)

Merge-dən əvvəl: (74359, 27)

In [82]:
accidents_weather_df = accidents_df.merge(
    weather_df,
    on=[
        'Grid_Latitude',
        'Grid_Longitude',
        'Weather_Hour'
    ],
    how='left'
)

In [83]:
print('Merge-dən sonra:', accidents_weather_df.shape)

Merge-dən sonra: (74359, 33)

In [84]:
weather_columns = [
    'temperature_2m',
    'rain',
    'snowfall',
    'weather_code',
    'cloud_cover',
    'wind_speed_10m'
]

accidents_weather_df[weather_columns].isnull().sum()

temperature_2m    0
rain              0
snowfall          0
weather_code      0
cloud_cover       0
wind_speed_10m    0
dtype: int64

In [85]:
accidents_weather_df[
    [
        'Accident_Index',
        'Weather_Hour',
        'Grid_Latitude',
        'Grid_Longitude',
        'temperature_2m',
        'rain',
        'snowfall',
        'weather_code',
        'cloud_cover',
        'wind_speed_10m'
    ]
].head()

,Accident_Index,Weather_Hour,Grid_Latitude,Grid_Longitude,temperature_2m,rain,snowfall,weather_code,cloud_cover,wind_speed_10m
0,201301BS70003,2013-01-02 09:00:00,51.5,-0.2,4.4,0.0,0.0,3,100,11.9
1,201301BS70005,2013-01-04 08:00:00,51.5,-0.2,8.3,0.0,0.0,3,97,14.1
2,201301BS70006,2013-01-07 11:00:00,51.5,-0.2,7.3,0.0,0.0,3,100,11.8
3,201301BS70007,2013-01-10 10:00:00,51.5,-0.2,1.4,0.0,0.0,3,100,3.6
4,201301BS70009,2013-01-04 17:00:00,51.5,-0.2,9.0,0.0,0.0,3,89,11.2

In [86]:
len(accidents_df) == len(accidents_weather_df)

True

In [87]:
test_latitude = accidents_df.loc[0, 'Grid_Latitude']
test_longitude = accidents_df.loc[0, 'Grid_Longitude']
test_date = accidents_df.loc[0, 'Date'].strftime('%Y-%m-%d')

print(test_latitude)
print(test_longitude)
print(test_date)

51.5
-0.2
2013-01-02

In [88]:
air_quality_url = 'https://air-quality-api.open-meteo.com/v1/air-quality'

air_quality_params = {
    'latitude': test_latitude,
    'longitude': test_longitude,
    'start_date': test_date,
    'end_date': test_date,
    'hourly': [
        'pm2_5',
        'pm10',
        'nitrogen_dioxide',
        'european_aqi'
    ],
    'timezone': 'Europe/London',
    'domains': 'cams_europe'
}

air_response = requests.get(
    air_quality_url,
    params=air_quality_params,
    timeout=60
)

print(air_response.status_code)

200

In [89]:
air_quality_data = air_response.json()

air_quality_test_df = pd.DataFrame(
    air_quality_data['hourly']
)

air_quality_test_df.head()

               time  pm2_5  pm10  nitrogen_dioxide  european_aqi
0  2013-01-02T00:00    6.3  16.9              25.1           NaN
1  2013-01-02T01:00    5.1  14.7              26.7          13.0
2  2013-01-02T02:00    5.3  14.2              19.8          13.0
3  2013-01-02T03:00    5.2  13.0              15.8          13.0
4  2013-01-02T04:00    5.1  13.3              16.4          14.0

In [90]:
air_quality_test_df.shape

(24, 5)

In [91]:
air_quality_test_df.columns

Index(['time', 'pm2_5', 'pm10', 'nitrogen_dioxide', 'european_aqi'], dtype='str')

In [92]:
import time

air_quality_list = []

In [93]:
for i in range(len(grid_df)):

    latitude = grid_df.loc[i, 'Grid_Latitude']
    longitude = grid_df.loc[i, 'Grid_Longitude']

    air_quality_params = {
        'latitude': latitude,
        'longitude': longitude,
        'start_date': '2013-01-01',
        'end_date': '2015-12-31',
        'hourly': [
            'pm2_5',
            'pm10',
            'nitrogen_dioxide',
            'european_aqi'
        ],
        'timezone': 'Europe/London',
        'domains': 'cams_europe'
    }

    success = False

    while success == False:

        air_response = requests.get(
            air_quality_url,
            params=air_quality_params,
            timeout=120
        )

        if air_response.status_code == 200:

            air_quality_data = air_response.json()

            temp_air_df = pd.DataFrame(
                air_quality_data['hourly']
            )

            temp_air_df['Grid_Latitude'] = latitude
            temp_air_df['Grid_Longitude'] = longitude

            air_quality_list.append(temp_air_df)

            print(
                len(air_quality_list),
                'of',
                len(grid_df),
                'completed'
            )

            success = True

            time.sleep(15)

        elif air_response.status_code == 429:

            print('Rate limit. Retrying this grid...')

            time.sleep(60)

        else:

            print(
                'Error:',
                latitude,
                longitude,
                air_response.status_code
            )

            success = True

1 of 34 completed
2 of 34 completed
3 of 34 completed
4 of 34 completed
5 of 34 completed
6 of 34 completed
7 of 34 completed
8 of 34 completed
9 of 34 completed
10 of 34 completed
11 of 34 completed
12 of 34 completed
13 of 34 completed
14 of 34 completed
15 of 34 completed
16 of 34 completed
17 of 34 completed
18 of 34 completed
19 of 34 completed
20 of 34 completed
21 of 34 completed
22 of 34 completed
23 of 34 completed
24 of 34 completed
25 of 34 completed
26 of 34 completed
27 of 34 completed
28 of 34 completed
29 of 34 completed
30 of 34 completed
31 of 34 completed
32 of 34 completed
33 of 34 completed
34 of 34 completed

In [94]:
len(air_quality_list)

34

In [95]:
air_quality_df = pd.concat(
    air_quality_list,
    ignore_index=True
)

air_quality_df.shape

(893520, 7)

In [96]:
air_quality_df.duplicated(
    subset=[
        'Grid_Latitude',
        'Grid_Longitude',
        'time'
    ]
).sum()

np.int64(0)

In [97]:
air_quality_df['time'] = pd.to_datetime(
    air_quality_df['time'],
    errors='coerce'
)

In [98]:
air_quality_df['time'] = pd.to_datetime(
    air_quality_df['time'],
    errors='coerce'
)

In [99]:
air_quality_df.isnull().sum()

time                  0
pm2_5                34
pm10                 34
nitrogen_dioxide     34
european_aqi        850
Grid_Latitude         0
Grid_Longitude        0
dtype: int64

In [100]:
air_quality_df.columns

Index(['time', 'pm2_5', 'pm10', 'nitrogen_dioxide', 'european_aqi',
       'Grid_Latitude', 'Grid_Longitude'],
      dtype='str')

In [101]:
air_quality_df['time'] = pd.to_datetime(
    air_quality_df['time'],
    errors='coerce'
)

air_quality_df.rename(
    columns={'time': 'Weather_Hour'},
    inplace=True
)

In [102]:
air_quality_df.duplicated(
    subset=[
        'Grid_Latitude',
        'Grid_Longitude',
        'Weather_Hour'
    ]
).sum()

np.int64(0)

In [103]:
final_df = accidents_weather_df.merge(
    air_quality_df,
    on=[
        'Grid_Latitude',
        'Grid_Longitude',
        'Weather_Hour'
    ],
    how='left'
)

In [104]:
print('Merge-dən əvvəl:', accidents_weather_df.shape)
print('Merge-dən sonra:', final_df.shape)

Merge-dən əvvəl: (74359, 33)
Merge-dən sonra: (74359, 37)

In [105]:
air_columns = [
    'pm2_5',
    'pm10',
    'nitrogen_dioxide',
    'european_aqi'
]

final_df[air_columns].isnull().sum()

pm2_5                1
pm10                 1
nitrogen_dioxide     1
european_aqi        33
dtype: int64

In [106]:
len(accidents_weather_df) == len(final_df)

True

In [107]:
final_df[
    [
        'Accident_Index',
        'Weather_Hour',
        'temperature_2m',
        'rain',
        'snowfall',
        'pm2_5',
        'pm10',
        'nitrogen_dioxide',
        'european_aqi'
    ]
].head()

,Accident_Index,Weather_Hour,temperature_2m,rain,snowfall,pm2_5,pm10,nitrogen_dioxide,european_aqi
0,201301BS70003,2013-01-02 09:00:00,4.4,0.0,0.0,7.5,17.5,44.9,22.0
1,201301BS70005,2013-01-04 08:00:00,8.3,0.0,0.0,6.3,14.4,23.9,20.0
2,201301BS70006,2013-01-07 11:00:00,7.3,0.0,0.0,14.5,19.6,45.4,28.0
3,201301BS70007,2013-01-10 10:00:00,1.4,0.0,0.0,30.6,41.5,58.1,51.0
4,201301BS70009,2013-01-04 17:00:00,9.0,0.0,0.0,10.8,17.7,41.9,21.0

In [108]:
final_df.shape

(74359, 37)

In [109]:
final_df['Accident_Index'].duplicated().sum()

np.int64(0)

In [110]:
final_df[
    ['pm2_5', 'pm10', 'nitrogen_dioxide', 'european_aqi']
].isnull().sum()

pm2_5                1
pm10                 1
nitrogen_dioxide     1
european_aqi        33
dtype: int64

In [111]:
final_df.to_csv("data/final_accidents_weather_air_quality.csv", index=False)

print('Final dataset saved successfully')
print(final_df.shape)

Final dataset saved successfully
(74359, 37)

In [112]:
final_df[
    final_df[
        ['pm2_5', 'pm10', 'nitrogen_dioxide', 'european_aqi']
    ].isnull().any(axis=1)
][
    [
        'Accident_Index',
        'Weather_Hour',
        'Grid_Latitude',
        'Grid_Longitude',
        'pm2_5',
        'pm10',
        'nitrogen_dioxide',
        'european_aqi'
    ]
]

,Accident_Index,Weather_Hour,Grid_Latitude,Grid_Longitude,pm2_5,pm10,nitrogen_dioxide,european_aqi
1012,201301CW10038,2013-01-01 02:00:00,51.5,-0.1,7.3,16.8,21.0,NaN
1023,201301CW10052,2013-01-01 22:00:00,51.5,-0.1,6.9,17.8,32.0,NaN
2498,201301EK40001,2013-01-01 08:00:00,51.5,-0.1,4.4,12.8,23.5,NaN
4029,201301FH10016,2013-01-01 15:00:00,51.5,-0.2,6.7,12.7,16.7,NaN
4598,201301GD10007,2013-01-01 03:00:00,51.6,-0.1,8.5,12.6,13.6,NaN
6881,201301JI40009,2013-01-01 06:00:00,51.6,0.1,4.6,9.0,8.7,NaN
6899,201301JI40028,2013-01-01 01:00:00,51.6,0.1,6.3,11.7,22.8,NaN
7560,201301KD50034,2013-01-01 09:00:00,51.6,0.2,4.4,12.6,16.8,NaN
8769,201301KG70028,2013-01-01 17:00:00,51.5,0.1,9.1,13.3,26.4,NaN
8772,201301KG70031,2013-01-01 16:00:00,51.6,0.1,6.6,11.4,14.6,NaN
8773,201301KG70032,2013-01-01 17:00:00,51.6,0.1,8.1,12.5,20.3,NaN
10498,201301MM70242,2013-01-01 14:00:00,51.5,-0.1,5.3,12.4,19.6,NaN
10571,201301MM70331,2013-01-01 23:00:00,51.5,-0.1,7.0,18.1,30.2,NaN
11229,201301PL60063,2013-01-01 14:00:00,51.5,-0.0,5.1,12.4,18.2,NaN
11239,201301PL60073,2013-01-01 08:00:00,51.5,-0.0,4.8,13.5,23.2,NaN
12026,201301PY20065,2013-01-01 22:00:00,51.4,0.1,7.7,17.3,28.5,NaN
13032,201301QK50003,2013-01-01 04:00:00,51.6,-0.2,5.4,7.4,10.1,NaN
13825,201301RG40067,2013-01-01 23:00:00,51.5,0.1,7.1,17.7,29.7,NaN
15766,201301TA00089,2013-01-01 13:00:00,51.5,-0.0,5.6,12.7,16.9,NaN
15823,201301TB00071,2013-01-01 09:00:00,51.5,-0.0,5.7,15.9,29.7,NaN
15824,201301TB00074,2013-01-01 03:00:00,51.5,-0.5,6.9,10.0,11.6,NaN
17171,201301VK30022,2013-01-01 14:00:00,51.4,-0.3,5.8,10.7,14.9,NaN
17172,201301VK30023,2013-01-01 18:00:00,51.4,-0.3,5.4,13.2,23.2,NaN
18028,201301WW50044,2013-01-01 04:00:00,51.4,-0.1,7.0,10.2,18.4,NaN
18876,201301XD80003,2013-01-01 19:00:00,51.5,-0.3,5.2,15.5,33.0,NaN
18899,201301XD80034,2013-01-01 23:00:00,51.5,-0.3,5.9,14.0,23.6,NaN
18901,201301XD80036,2013-01-01 00:00:00,51.5,-0.4,NaN,NaN,NaN,NaN
19932,201301XH30160,2013-01-01 12:00:00,51.6,-0.4,4.9,12.2,8.9,NaN
21082,201301YR90003,2013-01-01 14:00:00,51.6,-0.1,4.9,11.5,15.9,NaN
21246,201301YR90207,2013-01-01 01:00:00,51.6,-0.1,5.8,12.3,23.0,NaN
21908,201301ZD30086,2013-01-01 06:00:00,51.4,-0.1,4.3,10.8,13.6,NaN
21913,201301ZD30093,2013-01-01 09:00:00,51.3,-0.1,4.1,12.8,14.8,NaN
21918,201301ZD30098,2013-01-01 13:00:00,51.4,-0.1,6.3,11.3,18.7,NaN

In [113]:
final_df = final_df.dropna(
    subset=[
        'pm2_5',
        'pm10',
        'nitrogen_dioxide',
        'european_aqi'
    ]
).copy()

In [114]:
final_df = final_df.reset_index(drop=True)

In [115]:
print(final_df.shape)

final_df[
    ['pm2_5', 'pm10', 'nitrogen_dioxide', 'european_aqi']
].isnull().sum()

(74326, 37)

pm2_5               0
pm10                0
nitrogen_dioxide    0
european_aqi        0
dtype: int64

In [116]:
final_df.to_csv("data/final_accidents_weather_air_quality.csv", index=False)

print('Final cleaned dataset saved')
print(final_df.shape)

Final cleaned dataset saved
(74326, 37)

In [117]:
final_df

,Accident_Index,Longitude,Latitude,Accident_Severity,Date,Time,Day_of_Week,Number_of_Vehicles,Number_of_Casualties,Road_Type,...,temperature_2m,rain,snowfall,weather_code,cloud_cover,wind_speed_10m,pm2_5,pm10,nitrogen_dioxide,european_aqi
0,201301BS70003,-0.171402,51.486361,2,2013-01-02,09:08,4,2,1,6,...,4.4,0.0,0.0,3,100,11.9,7.5,17.5,44.9,22.0
1,201301BS70005,-0.173356,51.495115,3,2013-01-04,08:16,6,1,2,6,...,8.3,0.0,0.0,3,97,14.1,6.3,14.4,23.9,20.0
2,201301BS70006,-0.210767,51.518353,3,2013-01-07,11:45,2,1,1,6,...,7.3,0.0,0.0,3,100,11.8,14.5,19.6,45.4,28.0
3,201301BS70007,-0.209675,51.516808,3,2013-01-10,10:40,5,2,1,6,...,1.4,0.0,0.0,3,100,3.6,30.6,41.5,58.1,51.0
4,201301BS70009,-0.194332,51.492922,3,2013-01-04,17:47,6,2,1,2,...,9.0,0.0,0.0,3,89,11.2,10.8,17.7,41.9,21.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74321,2015480037777,-0.083941,51.511637,3,2015-12-29,16:41,3,2,1,6,...,10.4,0.0,0.0,3,98,19.3,4.5,11.2,17.4,22.0
74322,2015480038058,-0.091063,51.513641,2,2015-12-17,08:48,5,1,1,6,...,12.2,0.0,0.0,3,100,22.1,18.1,32.4,24.0,24.0
74323,2015480038223,-0.080030,51.515530,3,2015-12-24,13:07,5,1,1,6,...,10.9,1.3,0.0,61,100,36.1,3.2,8.1,10.4,23.0
74324,2015480038364,-0.077673,51.513333,3,2015-12-23,00:17,4,1,1,2,...,11.8,1.0,0.0,55,100,22.6,3.3,4.9,11.5,24.0
74325,2015480038764,-0.097002,51.516382,2,2015-12-05,00:42,7,1,1,2,...,10.6,0.0,0.0,3,100,30.1,4.8,17.9,9.8,24.0