In [ ]:


accidents_path = "../.vscode/data/raw/Accidents0515.csv (1).zip"
casualties_path = "../.vscode/data/raw/Casualties0515.csv.zip"
vehicles_path = "../.vscode/data/raw/Vehicles0515.csv.zip"

In [26]:
import pandas as pd
import numpy as np
import zipfile


with zipfile.ZipFile("../.vscode/data/raw/Accidents0515.csv (1).zip", 'r') as z:
    df_accidents = pd.read_csv(z.open("Accidents0515.csv"), low_memory=False)


with zipfile.ZipFile("../.vscode/data/raw/Casualties0515.csv.zip", 'r') as z:
    df_casualties = pd.read_csv(
        z.open("Casualties0515.csv"), 
        low_memory=False, 
        on_bad_lines='skip'  # Struktur xətası olan sətirləri keç (atla)
    )


with zipfile.ZipFile("../.vscode/data/raw/Vehicles0515.csv.zip", 'r') as z:
    df_vehicles = pd.read_csv(
        z.open("Vehicles0515.csv"), 
        low_memory=False, 
        on_bad_lines='skip'  # Hər ehtimala qarşı bura da əlavə edirik
    )

print(f" Qəzalar: {df_accidents.shape[0]} sətir")
print(f" Xəsarətlər: {df_casualties.shape[0]} sətir")
print(f" Avtomobillər: {df_vehicles.shape[0]} sətir")

 Qəzalar: 1780653 sətir
 Xəsarətlər: 2216720 sətir
 Avtomobillər: 3004425 sətir

In [27]:
df_accidents.info()

<class 'pandas.DataFrame'>
RangeIndex: 1780653 entries, 0 to 1780652
Data columns (total 32 columns):
 #   Column                                       Dtype
---  ------                                       -----
 0   Accident_Index                               str
 1   Location_Easting_OSGR                        float64
 2   Location_Northing_OSGR                       float64
 3   Longitude                                    float64
 4   Latitude                                     float64
 5   Police_Force                                 int64
 6   Accident_Severity                            int64
 7   Number_of_Vehicles                           int64
 8   Number_of_Casualties                         int64
 9   Date                                         str
 10  Day_of_Week                                  int64
 11  Time                                         str
 12  Local_Authority_(District)                   int64
 13  Local_Authority_(Highway)                    str
 14  1st_Road_Class                               int64
 15  1st_Road_Number                              int64
 16  Road_Type                                    int64
 17  Speed_limit                                  int64
 18  Junction_Detail                              int64
 19  Junction_Control                             int64
 20  2nd_Road_Class                               int64
 21  2nd_Road_Number                              int64
 22  Pedestrian_Crossing-Human_Control            int64
 23  Pedestrian_Crossing-Physical_Facilities      int64
 24  Light_Conditions                             int64
 25  Weather_Conditions                           int64
 26  Road_Surface_Conditions                      int64
 27  Special_Conditions_at_Site                   int64
 28  Carriageway_Hazards                          int64
 29  Urban_or_Rural_Area                          int64
 30  Did_Police_Officer_Attend_Scene_of_Accident  int64
 31  LSOA_of_Accident_Location                    str
dtypes: float64(4), int64(23), str(5)
memory usage: 512.2 MB

In [28]:
df_casualties.info()

<class 'pandas.DataFrame'>
RangeIndex: 2216720 entries, 0 to 2216719
Data columns (total 15 columns):
 #   Column                              Dtype
---  ------                              -----
 0   Accident_Index                      str
 1   Vehicle_Reference                   int64
 2   Casualty_Reference                  int64
 3   Casualty_Class                      int64
 4   Sex_of_Casualty                     int64
 5   Age_of_Casualty                     int64
 6   Age_Band_of_Casualty                int64
 7   Casualty_Severity                   int64
 8   Pedestrian_Location                 int64
 9   Pedestrian_Movement                 int64
 10  Car_Passenger                       int64
 11  Bus_or_Coach_Passenger              int64
 12  Pedestrian_Road_Maintenance_Worker  int64
 13  Casualty_Type                       int64
 14  Casualty_Home_Area_Type             int64
dtypes: int64(14), str(1)
memory usage: 281.2 MB

In [29]:
df_vehicles.info()

<class 'pandas.DataFrame'>
RangeIndex: 3004425 entries, 0 to 3004424
Data columns (total 22 columns):
 #   Column                            Dtype
---  ------                            -----
 0   Accident_Index                    str
 1   Vehicle_Reference                 int64
 2   Vehicle_Type                      int64
 3   Towing_and_Articulation           int64
 4   Vehicle_Manoeuvre                 int64
 5   Vehicle_Location-Restricted_Lane  int64
 6   Junction_Location                 int64
 7   Skidding_and_Overturning          int64
 8   Hit_Object_in_Carriageway         int64
 9   Vehicle_Leaving_Carriageway       int64
 10  Hit_Object_off_Carriageway        int64
 11  1st_Point_of_Impact               int64
 12  Was_Vehicle_Left_Hand_Drive?      int64
 13  Journey_Purpose_of_Driver         int64
 14  Sex_of_Driver                     int64
 15  Age_of_Driver                     int64
 16  Age_Band_of_Driver                int64
 17  Engine_Capacity_(CC)              int64
 18  Propulsion_Code                   int64
 19  Age_of_Vehicle                    int64
 20  Driver_IMD_Decile                 int64
 21  Driver_Home_Area_Type             int64
dtypes: int64(21), str(1)
memory usage: 541.5 MB

In [30]:
df_accidents.head()

,Accident_Index,Location_Easting_OSGR,Location_Northing_OSGR,Longitude,Latitude,Police_Force,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Date,...,Pedestrian_Crossing-Human_Control,Pedestrian_Crossing-Physical_Facilities,Light_Conditions,Weather_Conditions,Road_Surface_Conditions,Special_Conditions_at_Site,Carriageway_Hazards,Urban_or_Rural_Area,Did_Police_Officer_Attend_Scene_of_Accident,LSOA_of_Accident_Location
0,200501BS00001,525680.0,178240.0,-0.191170,51.489096,1,2,1,1,04/01/2005,...,0,1,1,2,2,0,0,1,1,E01002849
1,200501BS00002,524170.0,181650.0,-0.211708,51.520075,1,3,1,1,05/01/2005,...,0,5,4,1,1,0,0,1,1,E01002909
2,200501BS00003,524520.0,182240.0,-0.206458,51.525301,1,3,2,1,06/01/2005,...,0,0,4,1,1,0,0,1,1,E01002857
3,200501BS00004,526900.0,177530.0,-0.173862,51.482442,1,3,1,1,07/01/2005,...,0,0,1,1,1,0,0,1,1,E01002840
4,200501BS00005,528060.0,179040.0,-0.156618,51.495752,1,3,1,1,10/01/2005,...,0,0,7,1,2,0,0,1,1,E01002863

In [32]:
df_casualties.head()

,Accident_Index,Vehicle_Reference,Casualty_Reference,Casualty_Class,Sex_of_Casualty,Age_of_Casualty,Age_Band_of_Casualty,Casualty_Severity,Pedestrian_Location,Pedestrian_Movement,Car_Passenger,Bus_or_Coach_Passenger,Pedestrian_Road_Maintenance_Worker,Casualty_Type,Casualty_Home_Area_Type
0,200501BS00001,1,1,3,1,37,7,2,1,1,0,0,-1,0,1
1,200501BS00002,1,1,2,1,37,7,3,0,0,0,4,-1,11,1
2,200501BS00003,2,1,1,1,62,9,3,0,0,0,0,-1,9,1
3,200501BS00004,1,1,3,1,30,6,3,5,2,0,0,-1,0,1
4,200501BS00005,1,1,1,1,49,8,3,0,0,0,0,-1,3,-1

In [33]:
df_vehicles.head()

,Accident_Index,Vehicle_Reference,Vehicle_Type,Towing_and_Articulation,Vehicle_Manoeuvre,Vehicle_Location-Restricted_Lane,Junction_Location,Skidding_and_Overturning,Hit_Object_in_Carriageway,Vehicle_Leaving_Carriageway,...,Was_Vehicle_Left_Hand_Drive?,Journey_Purpose_of_Driver,Sex_of_Driver,Age_of_Driver,Age_Band_of_Driver,Engine_Capacity_(CC),Propulsion_Code,Age_of_Vehicle,Driver_IMD_Decile,Driver_Home_Area_Type
0,200501BS00001,1,9,0,18,0,0,0,0,0,...,1,15,2,74,10,-1,-1,-1,7,1
1,200501BS00002,1,11,0,4,0,3,0,0,0,...,1,1,1,42,7,8268,2,3,-1,-1
2,200501BS00003,1,11,0,17,0,0,0,4,0,...,1,1,1,35,6,8300,2,5,2,1
3,200501BS00003,2,9,0,2,0,0,0,0,0,...,1,15,1,62,9,1762,1,6,1,1
4,200501BS00004,1,9,0,18,0,0,0,0,0,...,1,15,2,49,8,1769,1,4,2,1

In [34]:
df_accidents.isnull().sum().sort_values(ascending=False)

LSOA_of_Accident_Location                      129471
Time                                              151
Longitude                                         138
Location_Easting_OSGR                             138
Latitude                                          138
Location_Northing_OSGR                            138
Accident_Severity                                   0
Accident_Index                                      0
Number_of_Vehicles                                  0
Number_of_Casualties                                0
Date                                                0
Day_of_Week                                         0
Local_Authority_(District)                          0
Local_Authority_(Highway)                           0
1st_Road_Class                                      0
Police_Force                                        0
1st_Road_Number                                     0
Road_Type                                           0
Junction_Detail                                     0
Speed_limit                                         0
2nd_Road_Class                                      0
2nd_Road_Number                                     0
Pedestrian_Crossing-Human_Control                   0
Junction_Control                                    0
Pedestrian_Crossing-Physical_Facilities             0
Light_Conditions                                    0
Road_Surface_Conditions                             0
Weather_Conditions                                  0
Special_Conditions_at_Site                          0
Carriageway_Hazards                                 0
Urban_or_Rural_Area                                 0
Did_Police_Officer_Attend_Scene_of_Accident         0
dtype: int64

In [35]:
df_casualties.isnull().sum().sort_values(ascending=False)

Accident_Index                        0
Vehicle_Reference                     0
Casualty_Reference                    0
Casualty_Class                        0
Sex_of_Casualty                       0
Age_of_Casualty                       0
Age_Band_of_Casualty                  0
Casualty_Severity                     0
Pedestrian_Location                   0
Pedestrian_Movement                   0
Car_Passenger                         0
Bus_or_Coach_Passenger                0
Pedestrian_Road_Maintenance_Worker    0
Casualty_Type                         0
Casualty_Home_Area_Type               0
dtype: int64

In [36]:
df_vehicles.isnull().sum().sort_values(ascending=False)

Accident_Index                      0
Vehicle_Reference                   0
Vehicle_Type                        0
Towing_and_Articulation             0
Vehicle_Manoeuvre                   0
Vehicle_Location-Restricted_Lane    0
Junction_Location                   0
Skidding_and_Overturning            0
Hit_Object_in_Carriageway           0
Vehicle_Leaving_Carriageway         0
Hit_Object_off_Carriageway          0
1st_Point_of_Impact                 0
Was_Vehicle_Left_Hand_Drive?        0
Journey_Purpose_of_Driver           0
Sex_of_Driver                       0
Age_of_Driver                       0
Age_Band_of_Driver                  0
Engine_Capacity_(CC)                0
Propulsion_Code                     0
Age_of_Vehicle                      0
Driver_IMD_Decile                   0
Driver_Home_Area_Type               0
dtype: int64

In [38]:
print(df_accidents.columns.tolist())
print("---")
print(df_casualties.columns.tolist())
print("---")
print(df_vehicles.columns.tolist())

['Accident_Index', 'Longitude', 'Latitude', 'Police_Force', 'Accident_Severity', 'Number_of_Vehicles', 'Number_of_Casualties', 'Date', 'Day_of_Week', 'Time', 'Local_Authority_(District)', 'Local_Authority_(Highway)', '1st_Road_Class', '1st_Road_Number', 'Road_Type', 'Speed_limit', 'Junction_Detail', 'Junction_Control', '2nd_Road_Class', '2nd_Road_Number', 'Pedestrian_Crossing-Human_Control', 'Pedestrian_Crossing-Physical_Facilities', 'Light_Conditions', 'Weather_Conditions', 'Road_Surface_Conditions', 'Special_Conditions_at_Site', 'Carriageway_Hazards', 'Urban_or_Rural_Area', 'Did_Police_Officer_Attend_Scene_of_Accident']
---
['Accident_Index', 'Vehicle_Reference', 'Casualty_Reference', 'Casualty_Class', 'Sex_of_Casualty', 'Age_of_Casualty', 'Age_Band_of_Casualty', 'Casualty_Severity', 'Pedestrian_Location', 'Pedestrian_Movement', 'Car_Passenger', 'Bus_or_Coach_Passenger', 'Pedestrian_Road_Maintenance_Worker', 'Casualty_Type', 'Casualty_Home_Area_Type']
---
['Accident_Index', 'Vehicle_Reference', 'Vehicle_Type', 'Towing_and_Articulation', 'Vehicle_Manoeuvre', 'Vehicle_Location-Restricted_Lane', 'Junction_Location', 'Skidding_and_Overturning', 'Hit_Object_in_Carriageway', 'Vehicle_Leaving_Carriageway', 'Hit_Object_off_Carriageway', '1st_Point_of_Impact', 'Was_Vehicle_Left_Hand_Drive?', 'Journey_Purpose_of_Driver', 'Sex_of_Driver', 'Age_of_Driver', 'Age_Band_of_Driver', 'Engine_Capacity_(CC)', 'Propulsion_Code', 'Age_of_Vehicle', 'Driver_IMD_Decile', 'Driver_Home_Area_Type']

In [37]:
cols_to_drop = ['Location_Easting_OSGR', 'Location_Northing_OSGR', 'LSOA_of_Accident_Location']
df_accidents.drop(columns=cols_to_drop, inplace=True)

In [40]:
cols_to_drop_casualties = ['Vehicle_Reference', 'Pedestrian_Location','Pedestrian_Movement', 'Car_Passenger', 'Bus_or_Coach_Passenger', 'Pedestrian_Road_Maintenance_Worker']

In [41]:
cols_to_drop_vehicles = ['Vehicle_IMD_Decile','Driver_IMD_Decile','Age_of_Vehicle','Engine_Capacity_.CC.','Propulsion_Code','Generic_Make_Model']

In [50]:
print(df_accidents.dtypes)

Accident_Index                                            str
Longitude                                             float64
Latitude                                              float64
Police_Force                                            int64
Accident_Severity                                       int64
Number_of_Vehicles                                      int64
Number_of_Casualties                                    int64
Date                                           datetime64[us]
Day_of_Week                                             int64
Time                                                      str
Local_Authority_(District)                              int64
Local_Authority_(Highway)                                 str
1st_Road_Class                                          int64
1st_Road_Number                                         int64
Road_Type                                               int64
Speed_limit                                             int64
Junction_Detail                                         int64
Junction_Control                                        int64
2nd_Road_Class                                          int64
2nd_Road_Number                                         int64
Pedestrian_Crossing-Human_Control                       int64
Pedestrian_Crossing-Physical_Facilities                 int64
Light_Conditions                                        int64
Weather_Conditions                                      int64
Road_Surface_Conditions                                 int64
Special_Conditions_at_Site                              int64
Carriageway_Hazards                                     int64
Urban_or_Rural_Area                                     int64
Did_Police_Officer_Attend_Scene_of_Accident             int64
Year                                                    int32
Month                                                   int32
DayOfWeek                                               int32
dtype: object

In [45]:
df_accidents['Date'] = pd.to_datetime(df_accidents['Date'], dayfirst=True)
print(df_accidents['Date'])

0         2005-01-04
1         2005-01-05
2         2005-01-06
3         2005-01-07
4         2005-01-10
             ...
1780648   2015-12-11
1780649   2015-12-02
1780650   2015-12-23
1780651   2015-12-26
1780652   2015-12-31
Name: Date, Length: 1780653, dtype: datetime64[us]

In [46]:
df_accidents['Year'] = df_accidents['Date'].dt.year
print(df_accidents['Year'])

0          2005
1          2005
2          2005
3          2005
4          2005
           ...
1780648    2015
1780649    2015
1780650    2015
1780651    2015
1780652    2015
Name: Year, Length: 1780653, dtype: int32

In [47]:
df_accidents['Month'] = df_accidents['Date'].dt.month
print(df_accidents['Month'])

0           1
1           1
2           1
3           1
4           1
           ..
1780648    12
1780649    12
1780650    12
1780651    12
1780652    12
Name: Month, Length: 1780653, dtype: int32

In [48]:
df_accidents['DayOfWeek'] = df_accidents['Date'].dt.dayofweek
print(df_accidents['DayOfWeek'])

0          1
1          2
2          3
3          4
4          0
          ..
1780648    4
1780649    2
1780650    2
1780651    5
1780652    3
Name: DayOfWeek, Length: 1780653, dtype: int32

In [49]:
print(df_casualties.dtypes)

Accident_Index                          str
Vehicle_Reference                     int64
Casualty_Reference                    int64
Casualty_Class                        int64
Sex_of_Casualty                       int64
Age_of_Casualty                       int64
Age_Band_of_Casualty                  int64
Casualty_Severity                     int64
Pedestrian_Location                   int64
Pedestrian_Movement                   int64
Car_Passenger                         int64
Bus_or_Coach_Passenger                int64
Pedestrian_Road_Maintenance_Worker    int64
Casualty_Type                         int64
Casualty_Home_Area_Type               int64
dtype: object

In [54]:
casualty_cols_with_minus1 = ['Pedestrian_Location','Pedestrian_Movement','Car_Passenger','Bus_or_Coach_Passenger','Pedestrian_Road_Maintenance_Worker','Casualty_Home_Area_Type']

for col in casualty_cols_with_minus1:
    df_casualties[col] = df_casualties[col].replace(-1, np.nan)

df_casualties['Age_of_Casualty'] = df_casualties['Age_of_Casualty'].replace(-1, np.nan)

print("Əvəzləmədən sonra -1-lərin sayı:")
print((df_casualties[casualty_cols_with_minus1] == -1).sum())

Əvəzləmədən sonra -1-lərin sayı:
Pedestrian_Location                   0
Pedestrian_Movement                   0
Car_Passenger                         0
Bus_or_Coach_Passenger                0
Pedestrian_Road_Maintenance_Worker    0
Casualty_Home_Area_Type               0
dtype: int64

In [51]:
print(df_vehicles.dtypes)

Accident_Index                        str
Vehicle_Reference                   int64
Vehicle_Type                        int64
Towing_and_Articulation             int64
Vehicle_Manoeuvre                   int64
Vehicle_Location-Restricted_Lane    int64
Junction_Location                   int64
Skidding_and_Overturning            int64
Hit_Object_in_Carriageway           int64
Vehicle_Leaving_Carriageway         int64
Hit_Object_off_Carriageway          int64
1st_Point_of_Impact                 int64
Was_Vehicle_Left_Hand_Drive?        int64
Journey_Purpose_of_Driver           int64
Sex_of_Driver                       int64
Age_of_Driver                       int64
Age_Band_of_Driver                  int64
Engine_Capacity_(CC)                int64
Propulsion_Code                     int64
Age_of_Vehicle                      int64
Driver_IMD_Decile                   int64
Driver_Home_Area_Type               int64
dtype: object

In [55]:
vehicle_cols_with_minus1 = ['Age_of_Driver','Age_of_Vehicle','Engine_Capacity_(CC)','Driver_IMD_Decile','Driver_Home_Area_Type','Journey_Purpose_of_Driver','Sex_of_Driver']

for col in vehicle_cols_with_minus1:
    df_vehicles[col] = df_vehicles[col].replace(-1, np.nan)

df_vehicles['Age_Band_of_Driver'] = df_vehicles['Age_Band_of_Driver'].replace(-1, np.nan)

print("Əvəzləmədən sonra -1-lərin sayı:")
print((df_vehicles[vehicle_cols_with_minus1] == -1).sum())

Əvəzləmədən sonra -1-lərin sayı:
Age_of_Driver                0
Age_of_Vehicle               0
Engine_Capacity_(CC)         0
Driver_IMD_Decile            0
Driver_Home_Area_Type        0
Journey_Purpose_of_Driver    0
Sex_of_Driver                0
dtype: int64

In [56]:
for name, df in [('accidents', df_accidents),
                  ('casualties', df_casualties),
                  ('vehicles', df_vehicles)]:
    print(f"\n=== {name} ===")
    print(f"Shape: {df.shape}")
    nulls = df.isnull().sum()
    print(f"NaN olan sütunlar:\n{nulls[nulls > 0]}")

=== accidents ===
Shape: (1780653, 32)
NaN olan sütunlar:
Longitude    138
Latitude     138
Time         151
dtype: int64

=== casualties ===
Shape: (2216720, 15)
NaN olan sütunlar:
Age_of_Casualty                         45920
Pedestrian_Location                        12
Pedestrian_Movement                        15
Car_Passenger                             404
Bus_or_Coach_Passenger                     38
Pedestrian_Road_Maintenance_Worker    1439022
Casualty_Home_Area_Type                322715
dtype: int64

=== vehicles ===
Shape: (3004425, 22)
NaN olan sütunlar:
Journey_Purpose_of_Driver     44921
Sex_of_Driver                    33
Age_of_Driver                330608
Age_Band_of_Driver           330608
Engine_Capacity_(CC)         788471
Age_of_Vehicle               874989
Driver_IMD_Decile            849921
Driver_Home_Area_Type        588611
dtype: int64

In [59]:
import os
os.makedirs('../data/processed', exist_ok=True)

df_accidents.to_csv('../data/processed/accidents_clean.csv', index=False)
df_casualties.to_csv('../data/processed/casualties_clean.csv', index=False)
df_vehicles.to_csv('../data/processed/vehicles_clean.csv', index=False)

print("Təmizlənmiş fayllar processed qovluğundadır")

Təmizlənmiş fayllar processed qovluğundadır

In [68]:
#UK-də 2005-2015-ci illərdə baş verən avtomobil qəzalarının son 3 ilini analiz edəcəm,dataset böyükdür effektiv analiz üçün 2013-2015 ci illəri götürürəm.
df_accidents_filtered = df_accidents[df_accidents['Year'] >= 2013].copy()

print(f"Tam data: {df_accidents.shape[0]:,} sətr")
print(f"2013-2015-ci illər: {df_accidents_filtered.shape[0]:,} sətr")
print(df_accidents_filtered['Year'].value_counts().sort_index())

Tam data: 1,780,653 sətr
2013-2015-ci illər: 425,038 sətr
Year
2013    138660
2014    146322
2015    140056
Name: count, dtype: int64

In [64]:
df_merged = df_accidents_filtered.merge(df_casualties, on='Accident_Index', how='left')
df_merged = df_merged.merge(df_vehicles, on='Accident_Index', how='left')

print(f"Merge olunmuş data (Filtered ilə birləşdirilmiş) : {df_merged.shape}")

Merge olunmuş data (Filtered ilə birləşdirilmiş) : (875241, 67)

In [67]:
# Processed-ə merge olunub,təmizlənmiş datanı əlavə edirəm 
df_accidents_filtered.to_csv('../data/processed/accidents_clean.csv', index=False)
df_merged.to_csv('../data/processed/merged_clean.csv', index=False)
print("processedd-ə merge_clean.csv əlavə olundu")

processedd-ə merge_clean.csv əlavə olundu